### ISSUE TITLE
Installation von lingpy

### ISSUE THREAD

**Issue by PascalCoenen** [LinguList/pyjs-seminar#2]
Bei der Installation von lingpy (lingpy-2.0.tar) erhalte ich folgende Fehlermeldung:
Command "python setup.py egg_info" failed with error code 1 in c:\users\coenen\appdata\local\temp\pip-build-u8xbwd\lingpy

**Comment by maurice-schleussinger** [comment]
`pip install lingpy==2.4.1-alpha-pre-release` hat das Problem für mich behoben. 

Mehr Details hier: https://github.com/lingpy/lingpy/issues/163

**Comment by LinguList** [comment]
okay, schließe das jetzt vorerst, bitte wieder öffnen, falls das problem nach wie vor besteht!
