### ISSUE TITLE
Falsche Lösungen für Aufgabe 9 der Probeklausr

### ISSUE THREAD

**Issue by maurice-schleussinger** [LinguList/pyjs-seminar#4]
**Aufgabe 9 der Probeklausur:**
Wann löst der folgende Befehl eine Fehlermeldung aus?

```
>>> a = ?
>>> a.append('x')

```

Als Anwortmöglichkeiten gibt die Musterlösung Antwort 1,2 und 4 vor.

Log der Python-Interactive-Shell für die Antwortmöglichkeiten 1-5:

```
$ python2
Python 2.7.10 (default, Jul 13 2015, 12:05:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a = list('python')
>>> a.append('x')
>>> 
>>> 
>>> a = list(range(10))
>>> a.append('x')
>>> 
>>> 
>>> a = ''.join(list('python'))
>>> a.append('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'str' object has no attribute 'append'
>>> 
>>> 
>>> a = ['hello','world']
>>> a.append('x')
>>> 
>>> 
>>> a = set('hello')
>>> a.append('x')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'set' object has no attribute 'append'
```

Es geben also Antwort 3 und 5 eine Fehlermeldung aus und nicht 1, 2 und 4.

**Comment by LinguList** [comment]
Okay, das ist ein klarer Fehler in der Klausur, die ich rumgeschickt habe. Ich erinnere mich sogar, dass ich das damals nachträglich korrigiert habe in meinem Lösungsschlüssel (es hatten Studenten fast 100 %). 

Rein theoretisch ist das natürlich aber auch klar: Eine Liste kann etwas anhängen, nicht ein set (das haben wir nicht besprochen, ist aber klares Python-Wissen, was allerdings nicht in der Klausur drankommen wird, da wir es eben nicht besprochen haben). Ein ''.join(irgendwas) wiederum erzeugt einen String, der auch keine append()-Funktion unterstützt. 

Ich werde noch mal das upgedatete schema an alle verschicken, damit es da keine Missverständnisse gibt.

Super, @M4urice, dass Du das durchprobiert hast! Vorbildliche Vorbereitung!
