### ISSUE TITLE
Latexfehler in basic.pdf

### ISSUE THREAD

**Issue by maurice-schleussinger** [LinguList/pyjs-seminar#6]
In `basic.pdf` auf Seite 67  bzw. [hier](https://github.com/LinguList/pyjs-seminar/blob/master/website/slides/tex/sitzung-3-2.tex#L32) wird die Formel nicht dargestellt.

**Comment by LinguList** [comment]
Korrekt. Das liegt daran, dass es noch keinen ordentlichen Konverter von HTML/JS/CSS zu LaTeX gibt. Wenn Du Zeit und Lust hast, kannst Du ja eventuell einen PR mit den Korrekturen machen. Ich werd leider so schnell noch nicht dazu kommen, die Formel auszubessern (ist ja zum Glück auch auf den Slides, die online stehen).

**Comment by digiretriever** [comment]
Die und ein paar kleinere habe ich schon bemängelt, allerings "nur" per Mail, das scheint ignoriert... Nur GitHub zählt... :(
Am einfachsten findet man alle Formeln, die nicht in Math-Mode umgeswitcht sind, in der PDF, indem man nach Dollar-Zeichen sucht...
MfG, BO

**Comment by LinguList** [comment]
Noch einfacher findet man die Fehler, indem man in die LaTeX-Dokumente geht und dort die Fehler behebt. Ich komme leider nicht dazu, weil es einfach zu viele andere Dinge zu tun gibt. Daher habe ich nur die Fehler korrigiert, die absolut wichtig waren. Das Problem ist, wie gesagt, die HTML zu TeX-Konvertierung. Wenn wer Zeit findet, das kurz zu ändern und das dann als Pull Request updated, wär das super. Ansonsten werde ich da so schnell nicht zu kommen, das zu beheben.
